Vagrant.configure("2") do |config|
  #Setup a Centos VM
  config.vm.define "demo" do |demo|
    demo.vm.box = "centos/7"
	demo.vm.box_version = "1804.02"
	demo.vm.provider "virtualbox" do |vb|
		vb.memory = "4096"
		vb.cpus = 1 
	end
	
	#Setup a shared folder
	demo.vm.synced_folder "./shared", "/vagrant", disabled: false
	
	#Don't check for OS updates on start
	demo.vm.box_check_update = false
	
	#Forward ports for SSH and HTTP
	demo.vm.network "forwarded_port", guest: 22, host: 1021
	demo.vm.network "forwarded_port", guest: 80, host: 80
	demo.vm.network "forwarded_port", guest: 443, host: 443
	demo.vm.network "forwarded_port", guest: 5000, host: 5000
	
	#Place your SSH keys here: keys/public and keys/private
	#There's probably a better way to do this!
	demo.ssh.insert_key = false
	demo.vm.provision "file", source: "keys/public", destination: "~/.ssh/authorized_keys"
    demo.ssh.private_key_path = ["keys/private", "~/.vagrant.d/insecure_private_key"]
	demo.vm.provision "shell", inline: <<-EOC
        sudo sed -i -e "\\#PasswordAuthentication yes# s#PasswordAuthentication yes#PasswordAuthentication no#g" /etc/ssh/sshd_config
        sudo systemctl restart sshd
	EOC
	
	#Set up the VM
	#An alternative would be to call a config mgmt tool instead
	config.vm.provision "shell", inline: <<-EOC
		#Install packages (including a newer kernel for docker compatibility)
		sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/7/x86_64/stable
		sudo rpm --import https://download.docker.com/linux/centos/gpg
		sudo yum -y install kernel.x86_64 vim docker-ce
		sudo systemctl daemon-reload && systemctl enable docker && systemctl restart docker
		#Let the vagrant user use docker
		sudo usermod -aG docker vagrant
	EOC

	end
end