version: "3.4"
services:

  web:
    image: nginx
    ports:
      - 80:80
    configs:
      - source: nginx-conf
        target: /etc/nginx/nginx.conf
    networks:
      - demo

  app:  
    image: friendlyhello
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    networks:
      - demo

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - data:/data
    hostname: redis
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - demo

networks:
  demo:

configs:
  nginx-conf:
    file: ./nginx.conf
      
volumes:
  data:
