version: "3"
services:

  web:
    image: nginx
    ports:
      - 8080:80
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - app
    restart: always
    
  db:
    image: postgres:9.4
    volumes:
      #- ./postgres/scripts/nextcloud:/docker-entrypoint-initdb.d:ro
      - postgres-data:/var/lib/postgresql/data
    hostname: postgres-hapi
    container_name: postgres-hapi_1
    networks:
      - demo

  app:  
    image: nextcloud:fpm
    ports:
      - 8080:80
    depends_on:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: always
	  
networks:
  demo:
    external:
      name: demo

volumes:
  postgres-data:

