version: "3"
services:

  web:
    image: nginx
    ports:
      - 8080:80
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - demo

  db:
    image: postgres:9.4
    volumes:
      #- ./postgres/scripts/nextcloud:/docker-entrypoint-initdb.d:ro
      - postgres-data:/var/lib/postgresql/data
    hostname: postgres-hapi
    networks:
      - demo

  app:  
    image: nextcloud:fpm
    ports:
      - 8081:80
    volumes:
      - nextcloud:/var/www/html
    networks:
      - demo

networks:
  demo:
    external:
      name: demo

volumes:
  postgres-data:
